name: Deploy

on:
  push:
    branhces:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to AWS EC2 Virtual Machine"
    runs-on: ubuntu-latest
    steps:
      #Skipping the set-up part, using library instead

      - name: Deploy changes to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_ROOT }}
            ./scripts/redeploy-site.bash --pull-update --with-docker
