name: Deploy

on:
  push:
    branhces:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to AWS EC2 Virtual Machine"
    runs-on: ubuntu-latest
    steps:
      #Skipping the set-up part, using library instead
      - name: Deploy changes to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_ROOT }}
            ./scripts/redeploy-site.bash --pull-update --with-docker

  check-container:
    name: "Check Container Status"
    runs-on: ubuntu-latest
    needs:
      - deploy
    steps:
      - name: Check the status of all docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PWD }}
          port: 22
          script: |
            cd ${{ secrets.PROJECT_ROOT }}
            docker compose ps --format json | jq "[.[] | {id: .ID, name: .Name, status: .State, exitCode: .ExitCode}]"

  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - deploy
      - check-container
    if: ${{ always() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
